spring:
  application:
    name: catalog-service
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: America/Mexico_City
    default-property-inclusion: non-null
  datasource:
    url: jdbc:oracle:thin:@delidev.cdyf4lkvosbp.us-west-2.rds.amazonaws.com:1521:delidev
    username: tpsdes
    password: TP$D1g1t4l$dm1n
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 15000
      max-lifetime: 30000
      connection-timeout: 30000
      pool-name: HikariCatalogServicePool
      connection-test-query: SELECT 1 FROM DUAL
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: true
