# Application Configuration

server:
  port: 8203

spring:
  application:
    name: product-service
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: America/Mexico_City
    default-property-inclusion: non-null
  datasource:
    url: jdbc:oracle:thin:@delidev.cdyf4lkvosbp.us-west-2.rds.amazonaws.com:1521:delidev
    username: tpsdes
    password: TP$D1g1t4l$dm1n
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 15000
      max-lifetime: 30000
      connection-timeout: 30000
      pool-name: HikariProductServicePool
      connection-test-query: SELECT 1 FROM DUAL
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    open-in-view: true
  data:
    web:
      pageable:
        size-parameter: pageSize
        page-parameter: pageNumber
        default-page-size: 300
        max-page-size: 3000
        one-indexed-parameters: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
